---
- name: "Install and configure Node_Exporter"
  hosts: all
  become: yes

  tasks:
  - name: "Include vars"
    include_vars:
      dir: vars/
    tags: include
  
  - name: "Create user for Mysql_Exporter"
    user:
      name: 'monitoring'
      shell: '/sbin/nologin'
      home: '{{ mysqld_dir }}'
    tags: user

  - name: "Install mysqld_exporter"
    copy:
      src: ./files/mysqld_exporter
      dest: /opt/mysqld_exporter/
      directory_mode: yes
      owner: 'monitoring'
      group: 'monitoring'
      mode: '0644'
    tags: copy_d

  - name: "Copy Mysqld_Exporter systemd-unit"
    template:
      src: 'systemd-unit-mysqld_exporter.yml.j2'
      dest: '/etc/systemd/system/mysqld_exporter.service'
      owner: 'monitoring'
      group: 'monitoring'
      mode: '0644'
      backup: 'yes'
    tags: copy

  - name: "Copy .my.cnf"
    template:
      src: '.my.cnf.j2'
      dest: '/opt/mysqld_exporter/.my.cnf'
      owner: 'monitoring'
      group: 'monitoring'
      mode: '0644'
      backup: 'yes'
    tags: copy

  - name: "Reload systemd and start"
    systemd:
      daemon_reload: yes
      enabled: yes
      masked: no
      state: started
      name: 'mysqld_exporter.service'
    tags: systemd
