---
- name: "Install and configure Pushgateway"
  hosts: all
  become: yes

  tasks:
  - name: "Include vars"
    include_vars:
      dir: vars/
    tags: include

  - name: "Create user for Pushgateway"
    user:
      name: 'monitoring'
      shell: '/sbin/nologin'
      home: '{{ push_dir }}'
    tags: user

  - name: "Download Pushgateway"
    get_url:
      url: https://github.com/prometheus/pushgateway/releases/download/v1.4.0/pushgateway-1.4.0.linux-amd64.tar.gz
      dest: /tmp/
      owner: 'monitoring'
      group: 'monitoring'
      mode: 0777
    tags: wget

  - name: "Rename Pushgateway dir"
    shell: |
      tar xzf /tmp/pushgateway-1.4.0.linux-amd64.tar.gz -C /tmp/ && cp -Rf /tmp/pushgateway-1.4.0.linux-amd64/* /opt/pushgateway/

  - name: "Copy Pushgateway systemd-unit"
    template:
      src: 'systemd-unit-pushgateway.yml.j2'
      dest: '/etc/systemd/system/pushgateway.service'
      owner: 'monitoring'
      group: 'monitoring'
      mode: '0644'
      backup: 'yes'
    tags: copy

  - name: "Reload systemd and start"
    systemd:
      daemon_reload: yes
      enabled: yes
      masked: no
      state: started
      name: 'pushgateway.service'
    tags: systemd
