---
- name: "Build whoami"
  hosts: all
  become: yes

  tasks:
  - name: "Include vars"
    include_vars:
      dir: vars/
    tags: include

  - name: "Install gcc"
    apt:
      name: 'gcc,cc-tool,make'
      update_cache: 'yes'
      state: 'present'
    tags: install

  - name: "Download GO"
    get_url:
      url: "https://golang.org/dl/go1.17.2.linux-amd64.tar.gz"
      dest: /tmp/
      owner: 'monitoring'
      group: 'monitoring'
      mode: 0755
    tags: wget_go

  - name: "Install GO"
    shell: |
      echo "PATH=$PATH:/usr/local/go/bin" >> /etc/profile && source /etc/profile
      cd /tmp/ && rm -rf /usr/local/go && tar -C /usr/local -xzf ./go1.17.2.linux-amd64.tar.gz
    tags: install_go
    ignore_errors: yes

  - name: "Download Mysql_Exporter"
    git:
      repo: "https://github.com/vozerov/whoamI.git"
      dest: "/tmp/mysqld_exporter/"
      version: master
      clone: yes
    tags: git_whoami

  - name: "Build"
    shell: |
      cd /tmp/mysqld_exporter/ && export PATH=$PATH:/usr/local/go/bin && make
    register: loginoutput
    failed_when: false
    no_log: True
    ignore_errors: yes
    tags: build 
